# Generated by Django 3.2.16 on 2022-12-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_author'
            ),
        ),
    ]
