# Generated by Django 3.2.16 on 2022-12-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221223_1200'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_author',
        ),
    ]
